name: linkedin
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - idna=3.4
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - libffi=3.4.4
  - libiconv=1.16
  - libsodium=1.0.18
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - openssl=1.1.1t
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - pywin32=305
  - pywinpty=2.0.10
  - pyzmq=25.0.2
  - requests=2.29.0
  - send2trash=1.8.0
  - setuptools=67.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - async-generator==1.10
    - chromedriver-autoinstaller==0.4.0
    - exceptiongroup==1.1.1
    - h11==0.14.0
    - numpy==1.24.3
    - outcome==1.2.0
    - pandas==2.0.2
    - selenium==4.11.2
    - sortedcontainers==2.4.0
    - tqdm==4.65.0
    - trio==0.22.0
    - trio-websocket==0.10.2
    - tzdata==2023.3
    - wsproto==1.2.0
